# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Monitor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Monitor.proto',
  package='WeatherMonitor',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rMonitor.proto\x12\x0eWeatherMonitor\"e\n\x07Monitor\x12\x11\n\tdatestamp\x18\x01 \x02(\x03\x12\x12\n\nfahrenheit\x18\x02 \x01(\x02\x12\x0f\n\x07\x63\x65lsius\x18\x03 \x01(\x02\x12\x10\n\x08pressure\x18\x04 \x01(\x02\x12\x10\n\x08humidity\x18\x05 \x01(\x05\"6\n\nStatistics\x12(\n\x07monitor\x18\x01 \x03(\x0b\x32\x17.WeatherMonitor.Monitor')
)




_MONITOR = _descriptor.Descriptor(
  name='Monitor',
  full_name='WeatherMonitor.Monitor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datestamp', full_name='WeatherMonitor.Monitor.datestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fahrenheit', full_name='WeatherMonitor.Monitor.fahrenheit', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='celsius', full_name='WeatherMonitor.Monitor.celsius', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='WeatherMonitor.Monitor.pressure', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='WeatherMonitor.Monitor.humidity', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=134,
)


_STATISTICS = _descriptor.Descriptor(
  name='Statistics',
  full_name='WeatherMonitor.Statistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='monitor', full_name='WeatherMonitor.Statistics.monitor', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=190,
)

_STATISTICS.fields_by_name['monitor'].message_type = _MONITOR
DESCRIPTOR.message_types_by_name['Monitor'] = _MONITOR
DESCRIPTOR.message_types_by_name['Statistics'] = _STATISTICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Monitor = _reflection.GeneratedProtocolMessageType('Monitor', (_message.Message,), {
  'DESCRIPTOR' : _MONITOR,
  '__module__' : 'Monitor_pb2'
  # @@protoc_insertion_point(class_scope:WeatherMonitor.Monitor)
  })
_sym_db.RegisterMessage(Monitor)

Statistics = _reflection.GeneratedProtocolMessageType('Statistics', (_message.Message,), {
  'DESCRIPTOR' : _STATISTICS,
  '__module__' : 'Monitor_pb2'
  # @@protoc_insertion_point(class_scope:WeatherMonitor.Statistics)
  })
_sym_db.RegisterMessage(Statistics)


# @@protoc_insertion_point(module_scope)
