// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherStation.Models;

namespace WeatherStation.Migrations
{
    [DbContext(typeof(WeatherStationContext))]
    [Migration("20190908190656_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherStation.Models.WeatherStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateStamp");

                    b.Property<int>("Humidity");

                    b.Property<decimal>("Pressure");

                    b.Property<decimal>("TempCelsius");

                    b.Property<decimal>("TempFahrenheit");

                    b.HasKey("Id");

                    b.ToTable("WeatherStats");
                });
#pragma warning restore 612, 618
        }
    }
}
